name: SilRokAIServerTest
services:
    app:
        build:
            context: ..
            dockerfile: .server/Dockerfile
        shm_size: "36gb"
        volumes:
            - ../.model/huggingface:/root/.cache/huggingface
            - ../.model/torch:/root/.cache/torch
            - ../logs:/workspaces/app/logs
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]

    nginx:
        image: nginx:latest
        ports:
            - "8080:443"
        volumes:
            - ../nginx/conf.d/test.conf:/etc/nginx/conf.d/test.conf
            - ../nginx/certbot/localhost:/etc/nginx/certs
        depends_on:
            - app
