name: SilRokAI
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        shm_size: "36gb"
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        ports:
            - "8080:8000"
