DIARIZATION_EMBED = "diarization_embed"
DIARIZATION_REFER = "diarization_refer"
DIARIZATION = "diarization"
METADATA = "metadata"
CONTEXT = "context"
CONTEXT_DONE = "context_done"

LLM_FLAGS = [
    METADATA,
    CONTEXT,
    CONTEXT_DONE,
]

DIARIZE_FLAGS =[
    DIARIZATION_EMBED,
    DIARIZATION_REFER,
    DIARIZATION,
]

FLAGS = [
    DIARIZATION_EMBED,
    DIARIZATION_REFER,
    DIARIZATION,
    METADATA,
    CONTEXT,
    CONTEXT_DONE,
]
