class settings:
  PROJECT_NAME = "SilRok AI server"
  PROJECT_VERSION = "0.1.0"

  THREAD_MAX_WORKERS = 20

  MODEL_SAMPLE_RATE = 16000 # 16kHz
  MIN_AUDIO_DURATION = 3 * MODEL_SAMPLE_RATE # 4 seconds
  
  REDIS_STR_HOST = "redis_str"
  REDIS_STR_PORT = 6379
  REDIS_STR_DB = 0
  REDIS_STR_DECODE_RESPONSES = True
  REDIS_STR_TTL = 10
  REDIS_STR_MAX_MEMORY = "10mb"
  REDIS_STR_MAX_MEMORY_POLICY = "noeviction" 

  REDIS_BYTE_HOST = "redis_byte"
  REDIS_BYTE_PORT = 6379
  REDIS_BYTE_DB = 0
  REDIS_BYTE_DECODE_RESPONSES = False
  REDIS_BYTE_TTL = 10
  REDIS_BYTE_MAX_MEMORY = "10mb"
  REDIS_STR_MAX_MEMORY_POLICY = "noeviction" 