class settings:
  PROJECT_NAME = "SilRok AI server"
  PROJECT_VERSION = "0.1.0"

  DEFAULT_SAMPLE_RATE = 16000

  MODEL_SIZE = "large-v3"
  MODEL_DEVICE = "cuda"
  MODEL_COMPUTE_TYPE = "int8"
  MODEL_BEAM_SIZE = 3
  MODEL_BATCH_SIZE = 8
  MODEL_SAMPLE_RATE = 16000

  MODEL_WORD_MAX_PREV_TIME = 3

  MODEL_SCENTENCE_MAX_PREV_SENTENCE = 1

  THREAD_MAX_WORKERS = 20

  MIN_AUDIO_DURATION = 2 * MODEL_SAMPLE_RATE # 2 seconds
  
  REDIS_STR_HOST = "redis_str"
  REDIS_STR_PORT = 6379
  REDIS_STR_DB = 0
  REDIS_STR_DECODE_RESPONSES = True
  REDIS_STR_TTL = 10
  REDIS_STR_MAX_MEMORY = "10mb"
  REDIS_STR_MAX_MEMORY_POLICY = "noeviction" 

  REDIS_BYTE_HOST = "redis_byte"
  REDIS_BYTE_PORT = 6379
  REDIS_BYTE_DB = 0
  REDIS_BYTE_DECODE_RESPONSES = False
  REDIS_BYTE_TTL = 10
  REDIS_BYTE_MAX_MEMORY = "10mb"
  REDIS_STR_MAX_MEMORY_POLICY = "noeviction" 